### ISSUE TITLE
windows不兼容

### ISSUE THREAD

**Issue by coolicer** [trekjs/trek#10]
在win8上试了，安装不上。

* 换了linux也装不上。
```
➜  workspace  npm i trek
 
> bcrypt@0.8.2 install /home/eep/workspace/node_modules/trek/node_modules/bcrypt
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: getaddrinfo ENOTFOUND iojs.org iojs.org:443
gyp ERR! stack     at errnoException (dns.js:25:10)
gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:75:26)
gyp ERR! System Linux 3.13.0-46-generic
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/eep/workspace/node_modules/trek/node_modules/bcrypt
gyp ERR! node -v v1.6.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i" "trek"
npm ERR! node v1.6.3
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/eep/workspace/npm-debug.log
```

**Comment by fundon** [comment]
你用 Node.js 还是 iojs?

**Comment by coolicer** [comment]
@fundon iojs

**Comment by fundon** [comment]
到 `bcrypt` 重新 `node-gyp rebuild` 试下

**Comment by coolicer** [comment]
还是装不了，你找一台新的机子看看有没有问题。

**Comment by fundon** [comment]
你可以装上一个版本试试 `npm i trek@0.0.11-dev`，我这边 Mac 没问题，一台 VPS 上也没有问题。
目前我在重构代码，精简，瘦身，像 `bcrypt` 这种第三方库，留给用户自己去装。

**Comment by coolicer** [comment]
@fundon 我就差mac没试了，win/linux都装不上

**Comment by coolicer** [comment]
我猜是我刚把vs删除了，可能把编译的东西删除了

**Comment by fundon** [comment]
嗯 检查下编译工具链，还有就是到 `bcrypt` 项目看看有没有相关 issues https://github.com/ncb000gt/node.bcrypt.js
